server.port=8080
spring.application.name=crud-clientes

spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.jackson.serialization.write-dates-as-timestamps=false

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=INFO

spring.main.allow-bean-definition-overriding=true